# --- A simple debugging template ---
# This will be used to prove the Helm chart can be rendered by ArgoCD.
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-app-helm-debug-configmap
data:
  # This proves that the values.yaml file is being read correctly.
  backendImage: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
  frontendImage: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
  message: "If you see this ConfigMap, the Helm chart is rendering correctly."
