apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-app.fullname" . }}-backend
  labels:
    app: {{ include "my-app.name" . }}-backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "my-app.name" . }}-backend
  template:
    metadata:
      labels:
        app: {{ include "my-app.name" . }}-backend
    spec:
      containers:
      - name: backend
        image: "{{ .Values.backend.repository }}:{{ .Values.backend.tag }}"
        imagePullPolicy: {{ .Values.backend.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.backend.port }}
          protocol: TCP
        resources:
          {{- toYaml .Values.resources.backend | nindent 12 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-app.fullname" . }}-frontend
  labels:
    app: {{ include "my-app.name" . }}-frontend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "my-app.name" . }}-frontend
  template:
    metadata:
      labels:
        app: {{ include "my-app.name" . }}-frontend
    spec:
      containers:
      - name: frontend
        image: "{{ .Values.frontend.repository }}:{{ .Values.frontend.tag }}"
        imagePullPolicy: {{ .Values.frontend.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.frontend.port }}
          protocol: TCP
        resources:
          {{- toYaml .Values.resources.frontend | nindent 12 }}
