# Stage 2: Serve with nginx
FROM nginx:alpine

COPY nginx.conf /etc/nginx/nginx.conf     # 👈 بدل ما تحط في conf.d، حطه في root config
COPY --from=build /app/build /usr/share/nginx/html

RUN addgroup -g 1001 -S nginx-group && \
    adduser -S nginx-user -u 1001 -G nginx-group

RUN chown -R nginx-user:nginx-group /usr/share/nginx/html \
 && chown -R nginx-user:nginx-group /etc/nginx \
 && chown -R nginx-user:nginx-group /var/cache/nginx \
 && chown -R nginx-user:nginx-group /var/log/nginx

USER nginx-user

EXPOSE 80

HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
  CMD curl -f http://localhost:80/ || exit 1

CMD ["nginx", "-g", "daemon off;"]
