apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
spec:
  project: default
  source:
    # This is the repository ArgoCD will watch
    repoURL: 'https://github.com/MostafaAssaff/NTI-Finale-Project.git'
    targetRevision: HEAD
    # This is the path to your Helm chart within the repository
    path: k8s/helm-chart
  destination:
    # This is where ArgoCD will deploy the application
    server: 'https://kubernetes.default.svc'
    namespace: default # Or any other namespace you want to deploy to
  syncPolicy:
    automated:
      prune: true
      selfHeal: true