# Default values for my-app
replicaCount: 2

backend:
  repository: 889818960214.dkr.ecr.us-west-2.amazonaws.com/my-app-repo
  tag: "1" # backend-tag
  pullPolicy: Always
  port: 8080
  
frontend:
  repository: 889818960214.dkr.ecr.us-west-2.amazonaws.com/my-app-repo
  tag: "1" # frontend-tag
  pullPolicy: Always
  port: 3000

service:
  backend:
    type: ClusterIP
    port: 8080
  frontend:
    type: LoadBalancer
    port: 80
    targetPort: 3000

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: my-app.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  backend:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  frontend:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

nodeSelector: {}
tolerations: []
affinity: {}
