# Default values for my-app
replicaCount: 2
backend:
  repository: 889818960214.dkr.ecr.us-west-2.amazonaws.com/my-app-repo
  tag: 33 # backend-tag (updated to existing tag)
  pullPolicy: Always
  port: 8080
  
frontend:
  repository: 889818960214.dkr.ecr.us-west-2.amazonaws.com/my-app-repo
  tag: 33 # frontend-tag (updated to existing tag)
  pullPolicy: Always
  port: 80  # Changed from 3000 to 80 to match nginx
  
service:
  backend:
    type: ClusterIP
    port: 8080
  frontend:
    type: LoadBalancer
    port: 80
    targetPort: 80  # Changed from 3000 to 80 to match nginx

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: my-app.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  backend:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  frontend:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

nodeSelector: {}
tolerations: []
affinity: {}
