# Default values for your Helm chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

frontend:
  name: frontend-app
  image:
    repository: 889818960214.dkr.ecr.us-west-2.amazonaws.com/frontend-app
    pullPolicy: IfNotPresent
    # Overridden by Jenkins pipeline with the specific build tag
    tag: "latest"
  service:
    type: LoadBalancer
    port: 80

backend:
  name: backend-app
  image:
    repository: 889818960214.dkr.ecr.us-west-2.amazonaws.com/backend-app
    pullPolicy: IfNotPresent
    # Overridden by Jenkins pipeline with the specific build tag
    tag: "latest"
  service:
    type: ClusterIP
    port: 8080 # Assuming your backend runs on 8080

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
