# Backend configuration
backend:
  replicaCount: 2
  image:
    repository: 889818960214.dkr.ecr.us-west-2.amazonaws.com/my-app-backend-repo
    tag: 61 # backend-tag
    pullPolicy: Always
  port: 3001
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  aws:
    region: us-west-2
    dynamoTableName: Todos
  serviceAccount:
    name: backend-sa

# Frontend configuration
frontend:
  replicaCount: 2
  image:
    repository: 889818960214.dkr.ecr.us-west-2.amazonaws.com/my-app-frontend-repo
    tag: 61 # frontend-tag
    pullPolicy: Always
  port: 8080
  resources:
    limits:
      cpu: 250m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

# Service configuration
service:
  backend:
    type: LoadBalancer
    port: 3001
  frontend:
    type: LoadBalancer
    port: 80
    targetPort: 80

# Ingress configuration
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: your-app.example.com
      paths:
        - path: /
          pathType: Prefix
          service: frontend
        - path: /api
          pathType: Prefix
          service: backend
  tls: []

# Auto-scaling configuration
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
