---
- name: 1. Download CloudWatch Agent for your region
  become: yes
  ansible.builtin.get_url:
    url: "https://s3.us-west-2.amazonaws.com/amazoncloudwatch-agent-us-west-2/ubuntu/amd64/latest/amazon-cloudwatch-agent.deb"
    dest: /tmp/amazon-cloudwatch-agent.deb
    mode: '0644'

- name: 2. Install the agent package
  become: yes
  ansible.builtin.apt:
    deb: /tmp/amazon-cloudwatch-agent.deb

- name: 3. Copy agent configuration file
  become: yes
  ansible.builtin.copy:
    src: cw_agent_config.json
    dest: /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
    owner: root
    group: root
    mode: '0644'

- name: 4. Start and enable the CloudWatch Agent service
  become: yes
  ansible.builtin.systemd:
    name: amazon-cloudwatch-agent
    state: restarted
    enabled: yes
